
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 21 00:54:45 CEST 2015
//----------------------------------------------------

package com.kompilatory.parser;

/** CUP generated interface containing symbol constants. */
public interface SqlSym {
  /* terminals */
  public static final int REAL_TYPE = 19;
  public static final int KEY = 9;
  public static final int REFERENCES = 10;
  public static final int DATE = 16;
  public static final int NOT = 6;
  public static final int IF = 5;
  public static final int LBRACKET = 20;
  public static final int ID = 2;
  public static final int RBRACKET = 21;
  public static final int TABLE = 4;
  public static final int VARCHAR = 13;
  public static final int CREATE = 3;
  public static final int COMMA = 23;
  public static final int INTEGER_TYPE = 18;
  public static final int EOF = 0;
  public static final int SERIAL = 17;
  public static final int error = 1;
  public static final int EXISTS = 7;
  public static final int PRIMARY = 8;
  public static final int INTEGER = 11;
  public static final int TIMESTAMP = 15;
  public static final int TEXT = 14;
  public static final int REAL = 12;
  public static final int APOSTROPHE = 22;
}

