
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package com.kompilatory.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int REAL_TYPE = 20;
  public static final int KEY = 10;
  public static final int REFERENCES = 11;
  public static final int DATE = 17;
  public static final int NOT = 7;
  public static final int IF = 6;
  public static final int LBRACKET = 21;
  public static final int ID = 2;
  public static final int RBRACKET = 22;
  public static final int TABLE = 5;
  public static final int NEW_LINE = 3;
  public static final int VARCHAR = 14;
  public static final int CREATE = 4;
  public static final int COMMA = 24;
  public static final int INTEGER_TYPE = 19;
  public static final int EOF = 0;
  public static final int SERIAL = 18;
  public static final int error = 1;
  public static final int EXISTS = 8;
  public static final int PRIMARY = 9;
  public static final int INTEGER = 12;
  public static final int TIMESTAMP = 16;
  public static final int TEXT = 15;
  public static final int REAL = 13;
  public static final int APOSTROPHE = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "NEW_LINE",
  "CREATE",
  "TABLE",
  "IF",
  "NOT",
  "EXISTS",
  "PRIMARY",
  "KEY",
  "REFERENCES",
  "INTEGER",
  "REAL",
  "VARCHAR",
  "TEXT",
  "TIMESTAMP",
  "DATE",
  "SERIAL",
  "INTEGER_TYPE",
  "REAL_TYPE",
  "LBRACKET",
  "RBRACKET",
  "APOSTROPHE",
  "COMMA"
  };
}

